debug: false
#actuator
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.sungjin.boardproject: debug
    #request , respons debug
    org.springframework.web.servlet: debug
    #jpa
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board  # mysql
    username: sj
    password: '0000'
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql8
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create #auto ddl create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: true
  sql.init.mode: always

---

#spring:  ## test
#  config.activate.on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board:mode=mysql
#    driver-class-name: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none

